services:
  fe:
    container_name: user-management-fe
    hostname: user-management-fe
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"