name: test
on:
  push:
    branches:
      - 'main'

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: install npm
        run: npm install

      - name: execute ESLint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: 'src/'
          fail_on_error: true

      - name: run tests
        run: npm test
